[package]
name = "tpfanctl"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
colored = "2.1.0"
libtpfanspeed = { path = "../libtpfanspeed" }
clap = { version = "4.5.9", features = ["derive"]}
